= Programaci칩n Competitiva

Algunos ejercicios de programaci칩n competitiva resueltos
en _Python_ y _C++_. Adem치s de recursos y tips para poder resolverlos.

== 쯇or qu칠 Python y C++?

La competencia oficial de _ICPC Chile_ se permiten 
las siguientes alternativas: C, C++, Java, Python, Kotlin.

Las alternativas de Java y Kotlin tienden a ser m치s veloces que Python, 
sin embargo requieren de m치s escritura de c칩digo, adem치s de uso de orientaci칩n
a objetos, lo cual puede complicar ciertas soluciones.

Python puede ser usado como pseudoc칩digo
y poder elaborar una soluci칩n inicial en papel o lenguaje de prototipado r치pido.
Puede ser usado para entregar la soluci칩n final, pero no hay garant칤as
de que la soluci칩n est칠 dentro de las restricciones de tiempo y memoria, como
lo son Java y C++.

C++ es el lenguaje m치s apropiado para entregar las soluciones finales
y cumplir tanto con las restricciones de tiempo y memoria. Tambi칠n
podr칤a ser C, pero C++ ofrece bibliotecas adicionales que facilitar칤an
la obtenci칩n de las soluciones.

== 쯇or qu칠 practicar programaci칩n competitiva?

Principalmente por que ayudan en el desarrollo de la l칩gica y matem치tica
y permiten practicar para ejercicios de entrevistas laborales.

Finalmente por que aprender de algoritmos, estructuras de datos y l칩gica
matem치tica son conceptos fundamentales para todo adepto a la inform치tica.

== Dificultades

Los problemas se pueden clasificar seg칰n su dificultad.
Para facilitar la interpretaci칩n se asociaron emojis seg칰n la dificultad.

.Dificultades y emojis
|===
| Emoji | Dificultad | Interpretaci칩n

| 游꼻 | 0 - 800 | Ejercicios de dificultad baja.
| 游뱁 | 900 - 1800 | Ejercicios de dificultad mediana.
| 游뱚 | 1900 - 2900 | Ejercicios de dificultad alta.
| 驕멆잺 | 3000 - 3400 | Ejercicios de dificultad extrema.
| 游놏 | 3500+ | Ejercicios de dificultad demoniaca.
|===

.Tags
|====
| Tags | Interpretaci칩n

| math, combinatorics, number theory | El ejercicio puede ser resuelto usando f칩rmulas matem치ticas, l칩gica, teor칤a de n칰meros o estad칤sticas.
| binary search | El ejercicio puede ser resuelto usando https://codeforces.com/blog/entry/143038[b칰squeda binaria en la respuesta].
| brute force | El ejercicio puede ser resuelto con fuerza bruta (considerando todos los posibles casos).
| greedy | El ejercicio puede ser resuelto con estrategias greedy.
| implementation | El ejercicio es simple de entender y resolver. Pero dentro de la implementacion esta el desafio (puede haber casos borde o gran cantidad de datos).
|====

== Recursos

- https://codeforces.com[Code Forces]. Principal fuente de problemas y evaluador de soluciones.

- https://www.buscalibre.cl/libro-grokking-algorithms-second-edition/9781633438538/p/55853430[Libro Grokking Algorithms] (ISBN: 9781633438538). Libro con informaci칩n valiosa para entender algoritmos y estructuras de datos.

- https://uchile.progcomp.cl/apunte/prologo/introduccion/[Programaci칩n Competitiva Universidad de Chile].

- https://cipc.progcomp.cl/[Campamento de Programacion Competitiva UTFSM].

- https://onecompiler.com/[One Compiler]. Permite compilar c칩digo en Python y C++ de forma online y r치pida.

== Requisitos ICPC

Para los universitarios que deseen participar en las competencias
de la https://icpc.global/regionals/finder/TCP[ICPC Chile] tienen que tener m치ximo 23 a침os y m치ximo cinco a침os de carrera cursados.

- asciimath:["A침o Nacimiento M치ximo" = "A침o Actual" - 23]

Normalmente la competencia de clasificaci칩n al mundial se hace en Noviembre, 
con un peque침o torneo de preparaci칩n en Octubre.
