= New Year and Hurry

- L칤mite de tiempo por prueba: 1 segundo.
- L칤mite de memoria por prueba: 256 megabytes.
- https://codeforces.com/problemset/problem/750/A[C칩digo Original].
- Fecha: 13/09/2025.
- Dificultad: 游꼻 (800)
- Tags: binary search, brute force, implementation, math

Limak va a participar en un concurso el 칰ltimo d칤a de 2016. El concurso empezar치 a las _20:00_ y durar치 *cuatro horas*, exactamente hasta la medianoche. Habr치 asciimath:[n] problemas, ordenados por dificultad, es decir, el problema asciimath:[1] es el m치s f치cil y el problema asciimath:[n] es el m치s dif칤cil. Limak sabe que le tomar치 asciimath:[5췅i] minutos resolver el problema asciimath:[i]-칠simo.

Los amigos de Limak organizan una fiesta de A침o Nuevo y 칠l quiere llegar a la fiesta a la medianoche o antes. Necesita asciimath:[k] minutos para llegar desde su casa, donde participar치 en el concurso primero.

La pregunta es: 쮺u치ntos problemas puede resolver Limak si quiere llegar a la fiesta a tiempo?


== Soluci칩n O(n) en C++

[source, cpp]
----
include::example$750a-new-year-hurry/solution-o(n).cpp[]
----


== Soluci칩n O(1) en C++

[source, cpp]
----
include::example$750a-new-year-hurry/solution-o(1).cpp[]
----